"""
Django settings for jb_quality project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

<<<<<<< HEAD
import os

import django_heroku
import dj_database_url
from decouple import config

=======
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lp-(ja5oo9(-ah3*u%*kac!g5p(sl#+rypm@qhiv1p90e6r(@b'

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'jbdjangoapp.herokuapp.com/']
=======
DEBUG = True

ALLOWED_HOSTS = []
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'whitenoise.runserver_nostatic',
    'django_filters',

    'dashboard.apps.DashboardConfig', # Dashboard app added
    
]

=======
     
    'crispy_forms', # package for custom form rendering https://django-crispy-forms.readthedocs.io/en/latest/
    'crispy_bootstrap5',
    'dashboard',
    'dashboard.templatetags',
  

 #   'dashboard.apps.DashboardConfig', # Dashboard app added
    
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
<<<<<<< HEAD
    
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
=======
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
]

ROOT_URLCONF = 'jb_quality.urls'

<<<<<<< HEAD
=======
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [         
#               BASE_DIR / "templates",
#               BASE_DIR / "templatetags"
     
#             ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],

#         # 'libraries':{
#         #     # 'duration_filter': 'templatetags.duration_filter',
#         #     'duration_filter' : 'dashboard.apps.templatetags.duration_filter'
        
#         # }


#         },
#     },
# ]



>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [
            
            BASE_DIR / "templates"
            
            ],
=======
        'DIRS': [BASE_DIR/"templates", BASE_DIR/"templatetags"],
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
<<<<<<< HEAD
=======

        # 'libraries':{

        #     'templatetags' : 'duration_filter'    
        # }


>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
        },
    },
]

<<<<<<< HEAD
=======




>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
WSGI_APPLICATION = 'jb_quality.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

<<<<<<< HEAD
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'degv0lep44641k',
#         'USER': 'jjxdjcdansywwy',
#         'PASSWORD': 'add6a7a40bc797a01aae25c7472e8caf027c03c4af827ff331d0d72f36738b7b',
#         'HOST': 'ec2-54-76-43-89.eu-west-1.compute.amazonaws.com',
#         'PORT': '5432',
#     }
# }

=======
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


USE_L10N = False

DATE_INPUT_FORMATS = [
    "%d/%m/%Y",
    '%Y-%m-%d'
]
<<<<<<< HEAD

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%i'
]

DATETIME_FORMAT="d/m/Y H:i"

=======
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
DATE_FORMAT = "d/m/Y"

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'Europe/Dublin'

USE_I18N = True

USE_TZ = True


<<<<<<< HEAD
LOGIN_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

=======
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
<<<<<<< HEAD



# Debugging in heroku live
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(process)d] [%(levelname)s] ' +
                        'pathname=%(pathname)s lineno=%(lineno)s ' +
                        'funcname=%(funcName)s %(message)s'),
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'testlogger': {
            'handlers': ['console'],
            'level': 'INFO',
        }
    }
}

DEBUG_PROPAGATE_EXCEPTIONS = True
COMPRESS_ENABLED = os.environ.get('COMPRESS_ENABLED', False)


# Email functionality TEST - NOT FOR PRODUCTION 
# seperate credentials when going to production  
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.office365.com' #smtp.office365.com #smtp-mail.outlook.com
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'jbdjango@outlook.com'
EMAIL_HOST_PASSWORD = 'JBengineering'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = "/static/"
django_heroku.settings(locals() ) #staticfiles=False
=======
>>>>>>> 0d69fb284d6ad3468a42eb034d9c2256bcc59ed3
