version: '3.9'

services:
  django_gunicorn:
    volumes:
      - data:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - data:/static
      - data:/media
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  data:
