version: '3.8'

services:
  app:
    build:
      context: . #use the Dockerfile in this working directory
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecretkey123 #alter this
      - ALLOWED_HOSTS=127.0.0.1 #alter this

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes: #makes docker compose create the new volume called "static_data"
  static_data: