version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static_data:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - ./static:/app/static/
      - ./media/images:/app/media/images
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static_data:
