version: '3.9'

services:
  django_gunicorn:
    volumes:
      - static_data:/app/static
      - media_data:/app/media/images
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static_data:/app/static
      - media_data:/app/media/images
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static
  media_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./media/images
