# Generated by Django 4.1 on 2022-08-10 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 22, 1), null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ncr_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
