# Generated by Django 4.0.5 on 2022-06-25 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard',
            new_name='DashboardModel',
        ),
    ]
