# Generated by Django 4.1 on 2022-08-04 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboardmodel_issue_affect_other_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 4, 15, 27), null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
            options={
                'verbose_name_plural': 'Production Companies',
            },
        ),
        migrations.CreateModel(
            name='OtherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
            options={
                'verbose_name_plural': 'Other Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('person_company_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.personorcompanyresponsible', verbose_name='Person or Company Responsible')),
            ],
        ),
    ]
