# Generated by Django 4.1 on 2022-08-05 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dashboardmodel_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='advice_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 19, 2), null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ncr_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
