# Generated by Django 4.0.5 on 2022-06-25 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dashboardmodel_issue_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='ncr_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dashboard.tag'),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='location',
            field=models.ManyToManyField(blank=True, to='dashboard.location'),
        ),
    ]
