# Generated by Django 4.0.6 on 2022-08-01 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dashboardmodel_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.areaofissue'),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='employee',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.employees'),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 20, 38), null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.locations'),
        ),
    ]
