# Generated by Django 4.0.5 on 2022-07-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_dashboardmodel_j_and_b_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='ncr_hyperlink',
        ),
    ]
