# Generated by Django 4.0.5 on 2022-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_employees_alter_dashboardmodel_issue_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='employee',
            field=models.ManyToManyField(blank=True, to='dashboard.employees'),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_solved',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
    ]
