# Generated by Django 4.0.6 on 2022-08-01 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dashboardmodel_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='area',
            field=models.ManyToManyField(blank=True, to='dashboard.areaofissue'),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 1, 20, 43), null=True),
        ),
    ]
