# Generated by Django 4.0.5 on 2022-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboardmodel_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
