# Generated by Django 3.2.15 on 2022-08-10 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220810_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ['name'], 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='dashboardmodel',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 14, 58), null=True),
        ),
    ]
