# Generated by Django 3.2.15 on 2022-08-06 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dashboardmodel_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='image_upload',
            field=models.ImageField(null=True, upload_to=('C:\\Users\\hp\\Desktop\\Main Project\\jb_quality_prj\\staticfiles', 'uploads')),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 6, 1, 9), null=True),
        ),
    ]
