# Generated by Django 3.2.15 on 2022-08-10 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220810_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 10, 15, 24), null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ncr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
