# Generated by Django 4.0.5 on 2022-06-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_dashboardmodel_issue_solved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='AreaOfIssue',
        ),
        migrations.RenameField(
            model_name='dashboardmodel',
            old_name='tags',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='dashboardmodel',
            old_name='date',
            new_name='closure_date',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
