# Generated by Django 4.0.6 on 2022-08-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_dashboardmodel_target_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default='01/08/2022', null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='target_completion_date',
            field=models.DateTimeField(blank=True, default='01/08/2022', null=True),
        ),
    ]
