# Generated by Django 4.0.5 on 2022-06-28 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_supervisorteam_dashboardmodel_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='supervisor',
            field=models.ManyToManyField(blank=True, to='dashboard.supervisorteam'),
        ),
        migrations.AlterField(
            model_name='supervisorteam',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
