# Generated by Django 4.0.5 on 2022-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_dashboardmodel_issue_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='corrective_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='downtime_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='estimated_completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='images',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='interim_containment_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='issue_affect_other_areas',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='issue_affect_other_areas_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='ncr_hyperlink',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='prevented_reoccurrence',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='result_validation_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='ncr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
