# Generated by Django 4.0.5 on 2022-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_dashboardmodel_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='closure_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
