# Generated by Django 4.0.5 on 2022-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_dashboardmodel_closure_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
