# Generated by Django 4.0.5 on 2022-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_dashboardmodel_issue_affect_other_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofissue',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='created',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='created',
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_affect_other_areas',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_solved',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='prevented_reoccurrence',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True),
        ),
    ]
