# Generated by Django 4.0.5 on 2022-07-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_dashboardmodel_issue_affect_other_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodel',
            name='advice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
