# Generated by Django 3.2.15 on 2022-08-08 20:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20220808_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='dashboardmodel',
            name='issue_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 8, 21, 46), null=True),
        ),
    ]
