# Generated by Django 4.0.5 on 2022-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_qualityissuesection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaIssue',
            new_name='DependantAreaIssue',
        ),
    ]
