# Generated by Django 4.0.5 on 2022-07-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_areaissue_dependantareaissue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependantareaissue',
            old_name='name',
            new_name='problem',
        ),
    ]
