# Generated by Django 4.0.5 on 2022-07-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_rename_name_dependantareaissue_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='issue_area',
        ),
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='quality_section',
        ),
        migrations.DeleteModel(
            name='DependantAreaIssue',
        ),
        migrations.DeleteModel(
            name='QualityIssueSection',
        ),
    ]
