# Generated by Django 4.0.5 on 2022-07-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_qualityissuesection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='issue_area',
        ),
        migrations.RemoveField(
            model_name='dashboardmodel',
            name='quality_section',
        ),
        migrations.DeleteModel(
            name='DependantAreaIssue',
        ),
        migrations.DeleteModel(
            name='QualityIssueSection',
        ),
    ]
