# Generated by Django 4.0.5 on 2022-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_issuearearesponsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofissue',
            name='area_responsible',
        ),
        migrations.AddField(
            model_name='areaofissue',
            name='area_responsible',
            field=models.ManyToManyField(blank=True, to='dashboard.issuearearesponsible'),
        ),
    ]
