# Generated by Django 4.0.5 on 2022-07-11 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_areaofissue_area_responsible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JandBIssues',
            fields=[
                ('issue_area_name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'JandB Issues',
            },
        ),
        migrations.CreateModel(
            name='OtherIssues',
            fields=[
                ('issue_area_name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Other Issues',
            },
        ),
        migrations.CreateModel(
            name='ProductionIssues',
            fields=[
                ('issue_area_name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Production Issues',
            },
        ),
        migrations.CreateModel(
            name='SupplierIssues',
            fields=[
                ('issue_area_name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Supplier Issues',
            },
        ),
        migrations.RenameModel(
            old_name='IssueAreaResponsible',
            new_name='CustomerIssues',
        ),
        migrations.AlterModelOptions(
            name='customerissues',
            options={'verbose_name_plural': 'Customer Issues'},
        ),
        migrations.RemoveField(
            model_name='areaofissue',
            name='area_responsible',
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='customer_issues',
            field=models.ManyToManyField(blank=True, to='dashboard.customerissues'),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='j_and_b_issue',
            field=models.ManyToManyField(blank=True, to='dashboard.jandbissues'),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='other_issues',
            field=models.ManyToManyField(blank=True, to='dashboard.otherissues'),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='production_issue',
            field=models.ManyToManyField(blank=True, to='dashboard.productionissues'),
        ),
        migrations.AddField(
            model_name='dashboardmodel',
            name='supplier_issue',
            field=models.ManyToManyField(blank=True, to='dashboard.supplierissues'),
        ),
    ]
