# Generated by Django 4.0.5 on 2022-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_dashboardmodel_client_dashboardmodel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodel',
            name='severity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
